name: Lint

on:
  pull_request:
    branches:
      - c4t
      - dev
  workflow_dispatch:
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55
      - name: run lint
        run: golangci-lint run --config .golangci.yml