name: Test

on:
  pull_request:
    branches:
      - c4t
      - dev
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: false
      - name: run test
        run: go test ./pkg/camino-license/